name = "CodecZstd"
uuid = "6b39b394-51ab-5f42-8807-6242bab2b4c2"
license = "MIT"
authors = ["Kenta Sato <bicycle1885@gmail.com>",
           "JuliaIO Github Organization"]
version = "0.8.2"

[deps]
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
Zstd_jll = "3161d3a3-bdf6-5164-811a-617609db77b4"

[compat]
TranscodingStreams = "0.9, 0.10"
Zstd_jll = "1.5.5"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
